# Generated by Django 6.0.6 on 2026-08-18 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinpapel', '0009_alter_historicalregistrofirma_verification_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(blank=True, default='', max_length=30)),
                ('identificador', models.CharField(blank=True, default='', max_length=30)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tasa_interes_moratorio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVersionFlujoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinpapel.versionflujo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.productoprueba')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sinpapel.estado')),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.productoprueba')),
            ],
        ),
    ]
